module.exports = {
  matches: {
    'PAD en acción': 'PAD en acción',
    'PAD en Acción': 'PAD en acción',
    'CEC': 'Centros Educativos Complementarios',
    'Centros Educativos Complementarios': 'Centros Educativos Complementarios',
    'Equipos de Orientación Escolar': 'Equipos de Orientación Escolar',
    'EOE': 'Equipos de Orientación Escolar',
    'Educación Artística - Teatro': 'Educación Artística - Teatro',
    'Educación Artística - Danza': 'Educación Artística - Danza',
    'Ed. Artística - Danza': 'Educación Artística - Danza',
    'Educación Artística - Música': 'Educación Artística - Música',
    'Ed. Artística - Música': 'Educación Artística - Música',
    'Educación Artística - Plástica': 'Educación Artística - Plástica',
    'Ed. Artística - Plástica': 'Educación Artística - Plástica',
    'Prácticas del Lenguaje': 'Prácticas del Lenguaje',
    'Matemática': 'Matemática',
    'Ciencias Sociales': 'Ciencias Sociales',
    'Educación Física': 'Educación Física',
    'Ciencias Naturales': 'Ciencias Naturales',
    'Inglés': 'Inglés',
    'Orientación PAD': 'EOE',
    'Temas Transversales': 'Temas Transversales'
  },
  alias: {
    'PAD en acción': 'pea',
    'PAD en Acción': 'pea',
    'CEC': 'cec',
    'Centros Educativos Complementarios': 'cec',
    'Equipos de Orientación Escolar': 'eoe',
    'EOE': 'eoe',
    'Educación Artística - Teatro': 'edart',
    'Educación Artística - Danza': 'edard',
    'Educación Artística - Música': 'edarm',
    'Ed. Artística - Música': 'edarm',
    'Educación Artística - Plástica': 'edarp',
    'Ed. Artística - Plástica': 'edarp',
    'Prácticas del Lenguaje': 'pdl',
    'Matemática': 'mat',
    'Ciencias Sociales': 'cs',
    'Educación Física': 'ef',
    'Ciencias Naturales': 'cn',
    'Inglés': 'ing',
    'Orientación PAD': 'eoe',
    'Temas Transversales': 'tt'
  }
};